### PR TITLE
Adds Usage instructions

### PR DESCRIPTION
**Pull request by DanielBunting**

### CODE REVIEW

**Comment by gummy7** [comment]
hi i'm having trouble using the foragebuddy? i did all the instruction there is but nothing

**Comment by eFlick** [comment]
Assuming you have it downloaded, you'll want to know where Puzzle Pirates is storing screenshots.

In-game, click on the "Ye" Tab -> Options -> General, and the default screenshot directory should be your desktop. In ForageBuddy, make sure you have selected this folder with the **Screenshot Folder** button.

image
image

Now ForageBuddy will use the same folder that Puzzle Pirates uses to store your screenshots. When you've completed a CI forage and receive a duty report like the following, you will want to take a screenshot in-game by pressing F12 or typing "/print" in chat. 

image

If your folders are set up correctly, you should be able to click the **Calculate Scores** button and ForageBuddy will output the scores.

**Comment by gummy7** [comment]
nope still didn't worked

**Comment by eFlick** [comment]
@gummy7 

What operating system is the program being run on? Does it output any errors? Are buttons not working? 

Be sure when taking screenshots of the game that they are being saved to the same folder and that the game confirms you've taken the screenshot in chat. You can also manually take screenshots on Windows with the "Snipping Tool" but you will have to manually save each image to a folder.

We will be releasing a video tutorial within the next two weeks. We are also working on simplifying image detection so users don't have to take screenshots, but there's no estimate on when this will be released. If you'd like help sooner feel free to add me on [Discord](https://discord.com/): Erik#7043.

**Comment by gummy7** [comment]
i've been doing that follow every instruction you've been saying but still won't work idk my friend already showed me, it works on him but it won't work on me what am i doing wrong? i did everything he said but still didn't go through at all

**Comment by gummy7** [comment]
do you have a video for it? i wanna know what am i doing wrong?

**Comment by DanielBunting** [comment]
Have you added Erik on Discord? He should be able to help! (Also, ensure you are using Large text [not as shown in Erik's screencapture]). Large text tends to work better with the OCR lib.

**Comment by gummy7** [comment]
i tried everything but still nothing sorry about this me commenting i just don't get it cause i tried everything there is unless you guys have a video to show it..

**Pull request merged**
